import { NextResponse } from "next/server";
import { requireApiUser } from "@/lib/api";
import { createAdminClient } from "@/lib/supabase/server";
import { generateTotpSecret } from "@/lib/totp";

type RouteContext = {
  params: Promise<{ id: string }>;
};

export async function POST(_request: Request, context: RouteContext) {
  const { user, response } = await requireApiUser();
  if (response) {
    return response;
  }

  const { id } = await context.params;
  const supabase = createAdminClient();
  const { data, error } = await supabase
    .from("employees")
    .update({ complete_verification_secret: generateTotpSecret() })
    .eq("id", id)
    .select("*")
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  await supabase.from("employee_activity_logs").insert({
    employee_id: id,
    action: "Authenticator reset",
    details: "Authorized Verification authenticator secret was regenerated by admin.",
    actor_id: user?.id || null
  });

  return NextResponse.json({ employee: data });
}
